version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-crendentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-crendentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-crendentials/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - pip3 install -r requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - echo "Shilpa@18" | docker login -u "shilpat18" --password-stdin "/hub.docker.com/repositories/shilpat18"
      - docker build -t "https://hub.docker.com/r/shilpat18/aws-devops-repo/shilpat18/python-aws-devops:latest" .
      - docker push "/hub.docker.com/repositories/shilpat18/python-aws-devops:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: ../AWS-DevOps

